<a href="https://colab.research.google.com/github/highway92/machine_learning/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%A8%B8%EC%8B%A4%EB%9F%AC%EB%8B%9D%20%EC%99%84%EB%B2%BD%20%EA%B0%80%EC%9D%B4%EB%93%9C/1__%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EB%B0%98%EC%9D%98_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B3%BC_%EC%83%9D%ED%83%9C%EA%B3%84_%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

array1 = np.array([1,2,3])
print(f"array1 type: {type(array1)}")
print(f"array1 array 형태: {array1.shape}")


array2 = np.array([[1,2,3],[2,3,4]])
print(f"array2 type: {type(array2)}")
print(f"array2 array 형태: {array2.shape}")

array3 = np.array([[1,2,3]])
print(f"array3 type: {type(array3)}")
print(f"array3 array 형태: {array3.shape}")

# ndarray로 변환을 원하는 객체를 인자로 입력하면 변환하여 반환합니다.
# ndarray.shape는 ndarray의 차원과 크기를 튜플형태로 나타내 줍니다.

print('array1 : {}차원, array2 : {}차원, array3 : {}차원'.format(array1.ndim,array2.ndim,array3.ndim))

# ndim 메서드를 사용하여 자료가 몇 차원의 자료인지 확인해 볼 수도 있습니다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1 : 1차원, array2 : 2차원, array3 : 2차원


In [10]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
# ndrray는 연산의 특성상 같은 데이터 타입만 가능함, 즉 한 개의 ndarray내 int, float가 공존 할 수 없음

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# 만약 다른 데이터 유형이 섞여있다면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄적용합니다.


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

# astype 메서드를 사용하여 형 변환을 해줄 수 있습니다.


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [13]:
# 테스트 데이터 생성

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2), dtype = 'int64')
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1]
 [1 1]
 [1 1]]
int64 (3, 2)


In [14]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# reshape를 통해 array 차원을 바꿔 줄 수 있다.


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,2)
print('array2 shape',array2.shape)

array3 = array1.reshape(2,-1)
print('array3 shape', array3.shape)
# -1인자는 어떤 차원의 ndarray도 2차원의 형태에 맞게 바꿔줍니다. 



[0 1 2 3 4 5 6 7 8 9]
array2 shape (5, 2)
array3 shape (2, 5)


In [17]:
array1 = np.arange(8)

array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)
# -1인자는 reshape (-1,1)와 같은 형태로 자주 사용됩니다.
# reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 형태로 변환됨을 보장합니다.

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [18]:
# 1붜 9까지의 1차원 ndarray 생성

array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하는 것에 주의

value = array1[2]
print('value',value)
print(type(value))
# 슬라이싱이나 값 수정 또한 파이썬 리스트와 동일하게 사용가능 합니다.


array1: [1 2 3 4 5 6 7 8 9]
value 3
<class 'numpy.int64'>


In [21]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(-1,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])
# 2차원 리스트의 indexing과 거의 동일하게 사용
# 정확히는 row, col이 아닌 axis 0, axis 1이 맞다.
# 3차원의 경우 axis0, axis1, axis2를 행, 열, 높이(혹은 가중치)로 이해하는 것이 편하다.


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [22]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))



[1 2 3]
<class 'numpy.ndarray'>


In [25]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d : \n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])

# 동일하게 axis0, axis1으로 이해 할 수 있다.


array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]


In [26]:
# 펜시 인덱싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())


array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]


In [28]:
# 불린 인덱싱
# 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용됨

array1d = np.arange(start=1, stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 값:', array3 )

array1d > 5
# ndarray 객체에 조건식만 붙이면 bool타입의 ndarray를 얻을 수 있다.

array1d > 5 불린 인덱싱 값: [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])